# name: Dependency Check

# on:
#   schedule:
#     - cron: "0 0 * * 0"   # weekly
#   workflow_dispatch:

# jobs:
#   scan:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Check dependencies
#         run: |
#           pip install safety
#           safety check -r requirements.txt
